##################################################
##                                              ##
##  _____ _    _ _____  _____ _                 ##
## / ____| |  | |_   _|/ ____| |                ##
##| |  __| |  | | | | | (___ | |__   ___  _ __  ##
##| | |_ | |  | | | |  \___ \| '_ \ / _ \| '_ \ ##
##| |__| | |__| |_| |_ ____) | | | | (_) | |_) |##
## \_____|\____/|_____|_____/|_| |_|\___/| .__/ ##
##                                       | |    ##
##                                       |_|    ##
##################################################



##################################################
#        Looking for a Custom Plugin?            #
#    Look no further! Visit ShulkerBox           #
#   To hire a Dev! A Developer will make it!     #
#          http://mcmart.org/                #
##################################################



## Tag in chat before text in chat from shop. e.g [GUIShop] Purchase Successful.
prefix: '[&cGUIShop&f]'

## Command used to open shop, DON'T PUT A /
buy-commands: 
    - 'buy'
    - 'shop'

## Command to open sell inventory, DON'T PUT A /
sell-commands:
    - 'sell'

############ Language settings ###############

#No permission message
no-permission: '&cNo Permission!'

#Disabled world message
disabled-world: '&cYou cannot use the shop from this world!'

#Use the escape key to close the shop instead of the back button.
escape-only: true

#The message for the amount you lose, E.G Cost, Or Price
cost: '&7Price'

#The message for the amount you get back AKA. Sell or Returned
return: '&7Sell'

#The 1st line of the message on shop items
line1: '&8To sell, click the item in your inv.'

#The 2nd line of the message on shop items
line2: '&6Must be the same quantity!'

#The 3rd line of the message on shop items
line3: 'Click to buy item of quantity'

#The 4th line of the message on shop items
line4: 'Shift+Click to buy 1 item'

#The text back button in the shops
back: '&cBack'

#The item the back button will be!
back-button-item: 'RED_STAINED_GLASS_PANE'

#The messaged displayed before the item amount.

purchased: '&fA purchase was made, and &c$'

## The second message displayed when you purchase an item.

## E.G 54$ Taken from your account.
taken: '&f was taken from your account.'

##  The words displayed before the amount needed.
not-enough-pre: '&fYou need &c$'

## The words displayed AFTER the amount needed.
not-enough-post: '&f to purchase this!'

## Text displayed before item name.
sold: '&fYour items were sold, and &a$'

##Second message when buying, Words AFTER the amount
## E.G 54$ "Added to your account"
added: '&f was added to your account.'

#When something magical goes wrong?
something-wrong: '&fSomething went wrong, contact an admin.'

#Message displayed when a player tries to sell blocks not matching the quantity.
in-stacks: '&fPlease sell in stacks of &c'

#Message when a player cannot sell a certain item.
cant-sell: '&fSorry, you are not able to sell that item.'

#Message when a player cannot buy a certain item.
cant-buy: '&fSorry, you are not able to buy that item.'

#When a player has a full inventory
full-inventory: '&cPlease empty your inventory!'

#The currency symbol
currency: '$'

#The suffix after the currency. E.G Dollars. Yen, etc.
currency-suffix: ''

#The title of a sign that players can click to open shop
sign-title: '[&cGUIShop&f]'

#Do want players to be able to access the shop ONLY using the sign? 
signs-only: false

signs-only-message: '&cYou can only access the shop by clicking a [&cGUIShop&f] sign!'

#Menu row count
menu-rows: 1

#Enable sound on purchase
enable-sound: true

#Purchase sound effect (You can find them here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html)
purchase-sound: 'ENTITY_PLAYER_LEVELUP'

#Enable in-game creator.
ingame-config: true

#The title of the quantity inventory.
qty-title: "&4Select Amount"

command-already: "&4You already own one or more of the specified commands!"

command-time-remaining: "&4Command Expires in: &e{TIME}"

command-expired: "&4Command has expired! Please purchase from shop!"

command-purchase: "&4This command can only be purchased from our shop!"

access-to: "&aAccess to Commands:"

##This will disable the usage to the command to everyone, unless purchased from shop or player is OP.
protected-commands:
  - '/fly'
  - '/suicide'



DisabledWorlds:
    -'Test'

##Menu Items
Rows: 1
1:
  Enabled: true
  Item: 'TNT'
  Shop: 'Raiding'
  Desc: '&8(&cBlow them up!&8)'
  Name: '&4Raiding'
2:
  Enabled: true
  Item: 'EMERALD'
  Shop: 'Ores'
  Desc: '&8(&fOres&8)'
  Name: '&aOres'
3:
  Enabled: true
  Item: 'WHEAT_SEEDS'
  Shop: 'Farming'
  Desc: '&8(&fFarming&8)'
  Name: '&eFarming'
4:
  Enabled: true
  Item: 'BONE_MEAL'
  Shop: 'Drops'
  Desc: '&8(&fDrops&8)'
  Name: '&cDrops'
5:
  Enabled: true
  Item: 'EXPERIENCE_BOTTLE'
  Shop: 'Brewing'
  Desc: '&8(&fBrewing&8)'
  Name: '&2Brewing'
6:
  Enabled: true
  Item: 'DIAMOND_HELMET'
  Shop: 'Gear'
  Desc: '&8(&fGear&8)'
  Name: '&bGear'
7:
  Enabled: true
  Item: 'SPAWNER'
  Shop: 'Spawners'
  Desc: '&8(&fSpawners&8)'
  Name: '&6Spawners'
8:
  Enabled: true
  Item: 'STONE'
  Shop: 'Blocks'
  Desc: '&8(&fBlocks&8)'
  Name: '&6Blocks'
  
## DO NOT TOUCH BELOW THIS LINE!
ver: 1.7

 ################################
 ## Developed by pablo67340    ##
 ## If you need any support    ##
 ## https://discord.gg/v7D6pCm ##
 ################################